version: '3.7'

services:
  server:
    env_file:
      - .env
    image: intersystemsdc/iris-community:latest
    ports:
      - 52773
    user: "51773"
    volumes:
      - ./init.db:/docker-entrypoint-initdb.d/
      - ./:/home/irisowner/conduit
      - ./db:/usr/irissys/mgr/CONDUIT
  web:
    build:
      context: web
      dockerfile: Dockerfile-${web:-vue}
    ports:
      - 80:80
